### ISSUE TITLE
Crash - Void fluid extractor + wooden fluid pipe

### ISSUE THREAD

**Issue by Zigian** [TheLimePixel/Modern-Skyblock-3#103]
Version 3.1.3.1
Hooked up a wooden fluid pipe with redstone engine to the factory tech fluid extractor.  It started extracting into an open blocks tank, then crashed the game.  I tried to load the save and it won't load it.  Have to revert to backup.

`A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dalapo.factech.auxiliary.FluidHandlerWrapper.drain(FluidHandlerWrapper.java:120)
	at buildcraft.transport.pipe.flow.PipeFlowFluids.extractSimple(PipeFlowFluids.java:267)
	at buildcraft.transport.pipe.flow.PipeFlowFluids.lambda$tryExtractFluid$0(PipeFlowFluids.java:194)
	at buildcraft.transport.pipe.flow.PipeFlowFluids.tryExtractFluidInternal(PipeFlowFluids.java:239)
	at buildcraft.transport.pipe.flow.PipeFlowFluids.tryExtractFluid(PipeFlowFluids.java:196)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.extractFluid(PipeBehaviourWood.java:116)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.extract(PipeBehaviourWood.java:100)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourWood.getPowerRequested(PipeBehaviourWood.java:129)
	at buildcraft.lib.engine.TileEngineBase_BC8.getPowerToExtract(TileEngineBase_BC8.java:352)
	at buildcraft.lib.engine.TileEngineBase_BC8.func_73660_a(TileEngineBase_BC8.java:316)

-- Block entity being ticked --
Details:
	Name: buildcraftcore:engine.wood // buildcraft.core.tile.TileEngineRedstone_BC8
	Block type: ID #6327 (tile.engineBlock // buildcraft.core.block.BlockEngine_BC8)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-996,87,-994), Chunk: (at 12,5,14 in -63,-63; contains blocks -1008,0,-1008 to -993,255,-993), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Actual block type: ID #6327 (tile.engineBlock // buildcraft.core.block.BlockEngine_BC8)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)`

**Comment by TheLimePixel** [comment]
Set remove Erroring Tile Entities to true in the forge config and don't use fluid pipes again.

**Comment by AlexIIL** [comment]
It would be really quite useful if you could post the full crash log so that this can be fixed properly in whatever mod is causing the buggy behaviour. Unfortunately what you've given in the main comment isn't enough to see what's going wrong. (At least assuming you even still have crash logs for when this happened).
