### ISSUE TITLE
Crash with Bibliocraft Clipboard Rendering

### ISSUE THREAD

**Issue by joakime** [TheLimePixel/Modern-Skyblock-3#115]
Using:

* Modern Skyblock 3 - version 3.1.3.2
* `BiblioCraft[v2.4.3][MC1.12.0].jar`

_Note: **not** using Optifine._

To reproduce:

* Get a Buildcraft Clipboard
* Add any notes to it
* `Shift + <Right-Click>` onto wall.

Results in the following crash ...

```
java.lang.NullPointerException: Rendering item
	at net.minecraftforge.client.model.obj.OBJModel$OBJBakedModel.buildQuads(OBJModel.java:1345)
	at net.minecraftforge.client.model.obj.OBJModel$OBJBakedModel.func_188616_a(OBJModel.java:1314)
	at jds.bibliocraft.models.ModelClipboard.func_188616_a(ModelClipboard.java:332)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:125)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:144)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:303)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:217)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:202)
	at mcjty.theoneprobe.rendering.RenderHelper.renderItemStack(RenderHelper.java:451)
	at mcjty.theoneprobe.apiimpl.client.ElementItemStackRender.render(ElementItemStackRender.java:28)
	at mcjty.theoneprobe.apiimpl.elements.ElementItemStack.render(ElementItemStack.java:35)
	at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:41)
	at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:41)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:429)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:277)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:117)
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:124)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_745_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:710)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:172)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
```

Server is unaffected, only impacts client. (makes sense)

Seems to be an old issue in Bibliocraft - Nuchaz/BiblioCraft#504

Still reporting it here, as it can impact users of your modpack too.

**Comment by joakime** [comment]
Looks like the core issue at bibliocraft is Nuchaz/BiblioCraft#490 (the prior referenced issue is a duplicate of this one).
Mentioning it here for github issue linking purposes.

**Comment by joakime** [comment]
Well, you could just disable the bibliocraft clipboard in your modpack ;-)
