### ISSUE TITLE
Game crashes when entering Aether

### ISSUE THREAD

**Issue by henkaa** [TheLimePixel/Modern-Skyblock-3#349]
My game seems to crash many times I try to enter Aether, other times I do not have time getting off in Aether and is teleported back to Overworld. Also, during loading of Aether, the game goes to "Not Responding" a few times.

Have complete crash report if it is of any interest. Here is the stacktrace

Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.legacy.aether.entities.passive.mountable.EntitySwet.isFriendly(EntitySwet.java:569)
	at com.legacy.aether.entities.util.EntityMountable.updateRider(EntityMountable.java:86)
	at com.legacy.aether.entities.util.EntityMountable.func_70071_h_(EntityMountable.java:72)
	at com.legacy.aether.entities.passive.mountable.EntitySwet.func_70071_h_(EntitySwet.java:91)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheLimePixel** [comment]
Go into the forge config and set removeErroringEntities to true. It seems like a Swet has been errored.

**Comment by henkaa** [comment]
I will try that :)
Is it a client or server config if I play on a server?

**Comment by TheLimePixel** [comment]
Server

**Comment by redsdracomancer** [comment]
Depends if the server is crashing, or if it is just your client. If the server is crashing then change the servers configure, but if it’s client try changing your clients config first, and if that doesn’t fix it then the servers config.

**Comment by henkaa** [comment]
Ok, then I try my client first.
Thanks for the quick responses.
