### ISSUE TITLE
Factory Tech update problem

### ISSUE THREAD

**Issue by attilavv** [TheLimePixel/Modern-Skyblock-3#614]
Hi,

Migrate from Modern Skyblock-3.3.1.4 to  Modern Skyblock-3.4.1.2

Server hosted with 6Go option. No change, original file no mod add, no mod removed.

In console i have ( without Factory Tech block placed )
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: mesh
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: mesh
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: gear
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: sawblade
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: gear
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: blade
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: gear
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: motor
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: drill
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: motor
[22:13:16] [Server thread/INFO] [Factory Tech]: Creating MachinePart: wire
[22:13:16] [Server thread/INFO] [Factory Tech]: hasWork: false
[22:13:16] [Server thread/INFO] [Factory Tech]: hasWork: false
[22:13:16] [Server thread/INFO] [Factory Tech]: hasWork: false
[22:13:16] [Server thread/INFO] [Factory Tech]: hasWork: false
[22:13:16] [Server thread/INFO] [Factory Tech]: hasWork: false
[22:13:17] [Server thread/INFO] [Factory Tech]: Creating MachinePart: mesh
[22:13:17] [Server thread/INFO] [Factory Tech]: Creating MachinePart: mesh

When placed Water Collector from Factory Tech i have 

[22:19:17] [Server thread/INFO] [Factory Tech]: Updated block at BlockPos{x=-989, y=85, z=-1007}
[22:19:17] [Server thread/INFO] [Factory Tech]: Updated block at BlockPos{x=-989, y=85, z=-1007}
[22:19:17] [Server thread/INFO] [Factory Tech]: Updated block at BlockPos{x=-989, y=85, z=-1007}
[22:19:17] [Server thread/INFO] [Factory Tech]: Updated block at BlockPos{x=-989, y=85, z=-1007}

 it is infiny message.
Same problem for Extraction Pump.

Cause many lag on server.

Edit : 

When i test version 3.4.1.3
Only download, unzip and run without copy of my world. I have a crash.
Run with start_server.bat
I have 16Gb of RAM.
Tested many time, download file 2 times.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Factory Tech (factorytech)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at dalapo.factech.auxiliary.MachineRecipes.addDrillRecipe(MachineRecipes.java:312)
	at dalapo.factech.auxiliary.MachineRecipes.addOreDictRecipes(MachineRecipes.java:355)
	at dalapo.factech.CommonProxy.postInit(CommonProxy.java:70)
	at dalapo.factech.FactoryTech.postInit(FactoryTech.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@55ecbafe from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 41 more
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 43 more

**Comment by TheLimePixel** [comment]
Well, while the debug code was removed on the latest version, it is highly unstable.
