### ISSUE TITLE
server crashes on start up

### ISSUE THREAD

**Issue by arbrenna** [TheLimePixel/Modern-Skyblock-3#639]
I get this crash log every time I try to load the server.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  RandomPatches (randompatches-1.12.2-1.2.0.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  FMLPlugin (elulib-0.1.12.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.8.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AstralCore (astralsorcery-1.12.2-1.9.1.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/4/18 3:41 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: crazypants.enderio.powertools.capacitor.CapacitorKey
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:602)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.powertools.capacitor.CapacitorKey
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	... 31 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.jar.Attributes.<init>(Attributes.java:84)
	at java.util.jar.Attributes.clone(Attributes.java:291)
	at sun.net.www.protocol.jar.URLJarFile.getManifest(URLJarFile.java:155)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:147)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:602)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 2.6.32-642.6.2.el6.x86_64
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 44945112 bytes (42 MB) / 358088704 bytes (341 MB) up to 358088704 bytes (341 MB)
	JVM Flags: 2 total; -XX:MaxPermSize=128m -Xmx384M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/common/util/TextTable$1
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  squeek.applecore.asm.TransformerModuleHandler
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
RandomPatches (randompatches-1.12.2-1.2.0.0.jar)
  com.therandomlabs.randompatches.RPTransformer
CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  team.chisel.ctm.client.asm.CTMTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.1.8.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
AstralCore (astralsorcery-1.12.2-1.9.1.jar)
  
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by TheLimePixel** [comment]
Yeah, after an EnderIO update certain blocks from EnderIO broke. Sadly that's all that this crash log tells us, so I have no idea which block it is exactly. Maybe try enabling removeErroringTileEntities in the forge config, if not, I guess remove every EIO block.
