### ISSUE TITLE
Game Crash when accessing ME Drive Fixture

### ISSUE THREAD

**Issue by noea4** [TheLimePixel/Modern-Skyblock-3#703]
The game throws a Java Exception for issuing a Payload that is over 32,767 bytes after attempting to access my ME Drive Fixture to check the status of my drives. I'm running on the latest version of the pack. This is a more detailed 

`[15:29:19] [JM-task-6/FATAL]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
[15:29:24] [Netty Local Client IO #2/ERROR]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[15:29:24] [Netty Local Client IO #2/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[15:29:24] [Netty Local Client IO #2/INFO]: [AstralSorcery] Cleaning client cache...
[15:29:24] [Netty Local Client IO #2/INFO]: [AstralSorcery] Cleared cached client data! Disconnected from server.`

I am unsure which mod in the pack is causing this at the moment, but I will update if I discover any more issues regarding this.

**Comment by noea4** [comment]
Update on this particular bug I came across. This particular instance seems to be isolated to viewing the Drives within the ME Drive Fixture after four drives are placed into the fixture (At least 16k sized). This big doesn't occur with the normal ME Drive. I'm about 70% sure it's something with the block itself causing the issue, but I'm unsure if another mod is conflicting with this particular block.

**Comment by DemonInTheCloset** [comment]
Have the same issue, have you found a workaround?

**Comment by DemonInTheCloset** [comment]
Breaking the fixture drops the drives on the ground, you can safely store them afterwards.
