### ISSUE TITLE
Server crashes on load after update

### ISSUE THREAD

**Issue by SuddenTurmoil** [TheLimePixel/Modern-Skyblock-3#730]
Server crashes upon world load after updating, error appears to be from AE2 and equivalent exchange interacting. I will downgrade the server and remove encoded EE patterns from players systems tomorrow and see if it survives an upgrade then. Crash report follows:
```
Description: Exception in server tick loop

java.lang.NoSuchMethodError: moze_intel.projecte.api.proxy.IEMCProxy.getValue(Lnet/minecraft/item/ItemStack;)I
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.createItemPattern(EMCCraftingPattern.java:108)
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.buildPattern(EMCCraftingPattern.java:91)
	at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.<init>(EMCCraftingPattern.java:31)
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.createPattern(EMCCraftingGrid.java:159)
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.addPattern(EMCCraftingGrid.java:94)
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.updatePatterns(EMCCraftingGrid.java:86)
	at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.onUpdateTick(EMCCraftingGrid.java:55)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:280)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:226)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2001_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mrtomwolf** [comment]
Trying to set up a fresh server and get stuck at Thread.java:748 as well.


```
[10:54:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[10:54:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[10:54:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[10:54:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:855)
[10:54:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:507)
[10:54:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[10:54:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.Thread.run(Thread.java:748)

```

**Comment by mrtomwolf** [comment]
So...this is a bit embarrassing but for me it was simply a matter of insufficient permissions on my linux server.

**Comment by SuddenTurmoil** [comment]
Ok, so, removed the PE book for providing PE patterns to AE2 and got a new error for a PE AE2 proxy block so I tried downgrading PE to 1.3.0 and Thaumic Equivalence to 1.0.2 and the world loaded and players could log in (once they also downgraded those two mods).

**Comment by TheLimePixel** [comment]
I'd honestly rather temporarily remove Equivalent Energistics than downgrade ProjectE.
