### ISSUE TITLE
Compact machine personal teleporter does not work

### ISSUE THREAD

**Issue by SuddenTurmoil** [TheLimePixel/Modern-Skyblock-3#731]
The personal teleporter does not work to enter a CM (though it will kick you to overworld if you use it inside one, just not to where you are supposed to be). It throws this error (truncated) in the server log.
```
at org.dave.compactmachines3.world.tools.TeleportationTools.teleportPlayerOutOfMachineDimension(TeleportationTools.java:100)
at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) [or.class:?]
at org.dave.compactmachines3.world.tools.TeleportationTools.teleportPlayerOutOfMachine(TeleportationTools.java:198)
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:763) [pa.class:?]
at org.dave.compactmachines3.item.ItemPersonalShrinkingDevice.func_77659_a(ItemPersonalShrinkingDevice.java:83)
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) [mb.class:?]
at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
```
It used to throw an error but work, now it throws an error and doesn't work. Also noticed the option to prevent players leaving their base is back on so I will disable that again and try compact machines once my server is vacant again. These two didn't play nice in some earlier version of the pack as well.

**Comment by RaveMaker** [comment]
i have the same issue, where can i find the "prevent players leaving their base" config file?
thx :)

**Comment by SuddenTurmoil** [comment]
It didn't fix the issue for me. I am going to follow up with CM's author
about it. The config for that (if you want to turn it off regardless of it
not fixing the CM issue) is under voidislandcontrol and set protection to
false.
