### ISSUE TITLE
Server crashing after update 

### ISSUE THREAD

**Issue by OldManCraft** [TheLimePixel/Modern-Skyblock-3#739]
I copied the Mod's, script's, and config folders over to update the server. 

Time: 8/28/18 2:38 AM

Description: Exception in server tick loop

java.lang.NoSuchMethodError: moze_intel.projecte.api.proxy.IEMCProxy.getValue(Lnet/minecraft/item/ItemStack;)I
at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.createItemPattern(EMCCraftingPattern.java:108)
at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.buildPattern(EMCCraftingPattern.java:91)
at com.mordenkainen.equivalentenergistics.integration.ae2.EMCCraftingPattern.<init>(EMCCraftingPattern.java:31)
at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.createPattern(EMCCraftingGrid.java:159)
at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.addPattern(EMCCraftingGrid.java:94)
at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.updatePatterns(EMCCraftingGrid.java:86)
at com.mordenkainen.equivalentenergistics.integration.ae2.cache.crafting.EMCCraftingGrid.onUpdateTick(EMCCraftingGrid.java:55)
at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
at appeng.me.Grid.update(Grid.java:280)
at appeng.hooks.TickHandler.onTick(TickHandler.java:226)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2008_TickHandler_onTick_TickEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by Peca21** [comment]
[This](https://github.com/Mordenkainen/EquivalentEnergistics/issues/98) is the problem. ProjectE has updated the API but Equivalent energistics didn't

**Comment by OldManCraft** [comment]
Do you not test before you put out a update. Seriously!

**Comment by TheLimePixel** [comment]
I always test a new world. I don't test a world that has everything from every mod.
