### ISSUE TITLE
Pulse Piston cannot be removed from the world

### ISSUE THREAD

**Issue by Tom-Broeders** [TheLimePixel/Modern-Skyblock-3#845]
**Describe the bug**
When placing down a pulse piston from factory tech ( on a remote server ), it cannot be removed from the world anymore. Not by mining, not by creative and not by commands. When hovering over it, wayla will say: "Waiting for server". Also, after attempting to remove it, other weird glitches start occurring. Like blocks not dropping when mined.

**To Reproduce**
1. Place down a pulse piston ( on a server )
2. Try to remove it

There are several pulse pistons in my world now at very inconvenient spots. Very annoying. I hope this can be fixed.

**Comment by Tom-Broeders** [comment]
A small update. After reviewing the server console, I found this crash report:

> 29.07 21:04:34 [Server] Server thread/WARN [minecraft/CommandHandler]: Couldn't process command: setblock ~ ~ ~1 minecraft:dirt
29.07 21:04:34 [Server] INFO java.lang.NoSuchFieldError: extension
29.07 21:04:34 [Server] INFO at dalapo.factech.tileentity.automation.TileEntityItemPusher.<init>(TileEntityItemPusher.java:37) ~[TileEntityItemPusher.class:?]
29.07 21:04:34 [Server] INFO at dalapo.factech.reference.TileReference.getTileFromID(TileReference.java:44) ~[TileReference.class:?]
29.07 21:04:34 [Server] INFO at dalapo.factech.block.BlockDirectionalTile.createTileEntity(BlockDirectionalTile.java:80) ~[BlockDirectionalTile.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782) ~[axw.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800) ~[axw.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.world.World.func_175625_s(World.java:2399) ~[amu.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.command.server.CommandSetBlock.func_184881_a(CommandSetBlock.java:106) ~[di.class:?]
29.07 21:04:34 [Server] INFO at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:88) ~[CommandOverride.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
29.07 21:04:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
29.07 21:04:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
29.07 21:04:34 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
29.07 21:04:34 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
29.07 21:04:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by Tom-Broeders** [comment]
Another update. Factory tech 1.6.6e seems to fix this problem. I will update this mod manually for now then (:
